package ca.magex.json.javadoc;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.stream.Collectors;

import org.apache.commons.io.FileUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import ca.magex.json.model.JsonArray;
import ca.magex.json.model.JsonObject;
import ca.magex.json.model.JsonText;
import ca.magex.json.util.FormattedStringBuilder;

public class JavadocDelegationBuilder {

	private static final Logger logger = LoggerFactory.getLogger(JavadocSlf4jDecoratorBuilder.class);
	
	public static void build(String description, File inputFile, String inputPackage, String inputClass, File outputFile, String outputPackage, String outputClass) throws IOException {
		logger.info("Building logger from " + inputFile.getAbsolutePath());
		if (!inputFile.isFile())
			throw new FileNotFoundException("Could not find input interface: " + inputFile.getAbsolutePath());
		JsonObject cls = JsondocBuilder.processFile(inputFile);
		FormattedStringBuilder sb = new FormattedStringBuilder();
		sb.append("package " + outputPackage + ";");
		sb.append("");
		sb.append("/**");
		sb.append(" * AUTO-GENERATED: This file is auto-generated by " + JavadocDelegationBuilder.class.getName());
		sb.append(" * ");
		sb.append(" * " + description);
		sb.append(" * ");
		sb.append(" * This delegate may be extended so that implementations can be kept clean if they don't need to implement every single field.");
		sb.append(" * ");
		sb.append(" * @author magex");
		sb.append(" */");
		sb.indent("public class " + outputClass + buildGenerics(cls, cls) + " implements " + inputPackage + "." + cls.getString("name") + buildGenerics(cls, cls) + " {");
		sb.append("");
		sb.append("private " + inputPackage + "." + cls.getString("name") + buildGenerics(cls, cls) + " delegate;");
		sb.append("");
		sb.indent("public " + outputClass + "(" + inputPackage + "." + cls.getString("name") + buildGenerics(cls, cls) + " delegate) {");
		sb.append("this.delegate = delegate;");
		sb.unindent("}");
		sb.append("");
		for (JsonObject method : cls.getArray("methods").values(JsonObject.class)) {
			buildMethod(sb, cls, method);
		}
		sb.unindent("}");
		
		logger.info("Writing file: " + outputFile.getAbsolutePath());
		FileUtils.writeStringToFile(outputFile, sb.toString(), StandardCharsets.UTF_8);
	}
	
	public static String buildGenerics(JsonObject cls, JsonObject obj) {
		if (!obj.contains("generics", JsonArray.class))
			return "";
		JsonArray generics = obj.getArray("generics");
		if (generics == null || generics.isEmpty())
			return "";
		return "<" + generics.stream().map(e -> {
			String type = ((JsonText)e).value();
			if (cls.getObject("imports").contains(type)) {
				return cls.getObject("imports").getString(type) + "." + type;
			} else {
				return type;
			}
		}).collect(Collectors.joining(", ")) + ">";
	}
	
	public static String buildType(JsonObject cls, JsonObject json) {
		if (!json.contains("type")) {
			return "void";
		} else if (json.contains("type", JsonText.class)) {
			if (json.getString("type").equals(cls.getString("name"))) {
				return cls.getString("package") + "." + json.getString("type");
			} else if (cls.getObject("imports").contains(json.getString("type"))) {
				return cls.getObject("imports").getString(json.getString("type")) + "." + json.getString("type");
			}
			return json.getString("type");
		} else if (json.contains("type", JsonObject.class)) {
			StringBuilder sb = new StringBuilder();
			if (cls.getObject("imports").contains(json.getObject("type").getString("class"))) {
				sb.append(cls.getObject("imports").getString(json.getObject("type").getString("class")) + "." + json.getObject("type").getString("class"));
			} else {
				sb.append(json.getObject("type").getString("class"));
			}
			sb.append(buildGenerics(cls, json.getObject("type")));
			return sb.toString();
		} else {
			return json.get("type").toString();
		}
	}
	
	private static void buildMethod(FormattedStringBuilder sb, JsonObject cls, JsonObject method) {
		String methodParams = !method.contains("parameters") ? "" :
			method.getArray("parameters", JsonObject.class).stream()
				.map(o -> buildType(cls, o) + " " + o.getString("name"))
				.collect(Collectors.joining(", "));
		String invokeParams = !method.contains("parameters") ? "" :
			method.getArray("parameters", JsonObject.class).stream()
			.map(o -> o.getString("name"))
			.collect(Collectors.joining(", "));
		String throwable = !method.contains("exceptions") ? "" :
			" throws " + method.getArray("exceptions", String.class).stream()
				.map(e -> cls.getObject("imports").getString(e) + "." + e).collect(Collectors.joining(", "));
		String returnType = buildType(cls, method);
		sb.append("@Override");
		sb.indent("public " + returnType + " " + method.getString("name") + "(" + methodParams + ")" + throwable + " {");
		if (returnType.equals("void")) {
			sb.append("delegate." + method.getString("name") + "(" + invokeParams + ");");
		} else {
			sb.append("return delegate." + method.getString("name") + "(" + invokeParams + ");");
		}
		sb.unindent("}");
		sb.append("");
	}
	
}
