apiVersion: v1
kind: Service
metadata:
  name: {{ include "crm-auth-spring-boot-server.fullname" . }}
  labels:
    {{- include "crm-auth-spring-boot-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.application.port }}
      protocol: TCP
  {{- if not .Values.service.omitClusterIP }}
    {{ with .Values.service.clusterIP }}clusterIP: {{ quote . }}{{ end }}
  {{- end }}
  selector:
    {{- include "crm-auth-spring-boot-server.selectorLabels" . | nindent 4 }}
